### ISSUE TITLE
Game Failing to Build (because of extension?)

### ISSUE THREAD

**Issue by Hornbuckle-Who** [YoYoGames/GMEXT-Steamworks#31]
I am trying to add steam achievement functionality into my game. Whenever the extension is in my project, trying to build my game always fails with the same message. I even tested it with a blank project and the same message appears. My GMS is on the latest possible version and my steamworks SDK is version 1.55 (as suggested by the ext). Everything seems to compile fine until the very end, at which point output says:

System.FormatException: Input string was not in a correct format.
at System.Text.StringBuilder.FormatError()
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.IO.StreamWriter.WriteFormatHelper(String format, ParamsArray args, Boolean appendNewLine)
at System.IO.StreamWriter.WriteLine(String format, Object arg0)
at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object arg0)
at System.Console.WriteLine(String format, Object arg0)
at Igor.Command.ExecuteCommandSync(String _command, String _args, Boolean _fail_on_error, String _cwd, YYDictionary`2 _env, Boolean as_admin, String timingKey, Boolean _fQuiet)
at Igor.Utils.ExecUserCmdStep(String fileName)
at Igor.Utils.RunUserCmdStep(String _basename)
at Igor.BaseTargetBuilder.PostBuildStep()
at Igor.WindowsBuilder.Compile(Boolean _exe)
at Igor.WindowsBuilder.Deploy(Boolean _exe)
at Igor.WindowsBuilder.Run()
Igor complete.
elapsed time 00:00:12.1695029s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.6.0.139/bin/igor/windows/x64/Igor.exe" -j=8 -options="C:\Users\chaan\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 08/27/2023 23:05:00
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

As soon as I get rid of the extension my game builds correctly (but obviously crashes due to no longer understanding the steamworks ext related functions that are called as soon as the game starts). I don't know enough to work out what the problem actually is, and nobody on the internet seemed to have this exact issue.

**Comment by Hornbuckle-Who** [comment]
Apparently it works just fine on another computer. Sorry to bother whomever this may have bothered.
